import {
  AuditLevel,
  InterviewStatus,
  InterviewType,
  Recommendation,
  SeniorityLevel,
} from "../../generated/prisma/enums";

const DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;

export function daysFromNow(offset: number) {
  return new Date(Date.now() + offset * DAY_IN_MILLISECONDS);
}

export const USER = {
  id: "11111111-1111-4111-8111-111111111111",
  name: "Main Interviewer",
  email: "interviewer@example.com",
  role: "interviewer",
} as const;

export const CANDIDATES = [
  {
    id: "22222222-2222-4222-8222-222222222222",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    targetRole: "Frontend Engineer",
    seniority: SeniorityLevel.MIDDLE,
    yearsExperience: 3,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    firstName: "Bob",
    lastName: "Martinez",
    email: "bob.martinez@example.com",
    targetRole: "Backend Engineer",
    seniority: SeniorityLevel.SENIOR,
    yearsExperience: 7,
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    firstName: "Carol",
    lastName: "Nguyen",
    email: "carol.nguyen@example.com",
    targetRole: "Full-stack Engineer",
    seniority: SeniorityLevel.JUNIOR,
    yearsExperience: 1,
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    firstName: "David",
    lastName: "Lee",
    email: "david.lee@example.com",
    targetRole: "Technical Lead",
    seniority: SeniorityLevel.LEAD,
    yearsExperience: 12,
  },
] as const;

export const INTERVIEWS = [
  {
    id: "66666666-6666-4666-8666-666666666666",
    title: "Alice - Frontend Technical",
    type: InterviewType.TECHNICAL,
    status: InterviewStatus.COMPLETED,
    scheduledAtOffset: -10,
    durationMinutes: 60,
    notes: "Frontend fundamentals and React architecture.",
    candidateId: CANDIDATES[0].id,
    interviewerId: USER.id,
  },
  {
    id: "77777777-7777-4777-8777-777777777777",
    title: "Bob - Backend System Design",
    type: InterviewType.SYSTEM_DESIGN,
    status: InterviewStatus.COMPLETED,
    scheduledAtOffset: -3,
    durationMinutes: 90,
    notes: "Distributed services and database design.",
    candidateId: CANDIDATES[1].id,
    interviewerId: USER.id,
  },
  {
    id: "88888888-8888-4888-8888-888888888888",
    title: "Carol - Coding Exercise",
    type: InterviewType.CODING,
    status: InterviewStatus.SCHEDULED,
    scheduledAtOffset: 2,
    durationMinutes: 60,
    notes: "TypeScript coding exercise.",
    candidateId: CANDIDATES[2].id,
    interviewerId: USER.id,
  },
  {
    id: "99999999-9999-4999-8999-999999999999",
    title: "David - Leadership",
    type: InterviewType.BEHAVIORAL,
    status: InterviewStatus.CANCELLED,
    scheduledAtOffset: 7,
    durationMinutes: 45,
    notes: "Cancelled at the candidate's request.",
    candidateId: CANDIDATES[3].id,
    interviewerId: null,
  },
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    title: "Bob - Follow-up Coding",
    type: InterviewType.CODING,
    status: InterviewStatus.COMPLETED,
    scheduledAtOffset: -1,
    durationMinutes: 60,
    notes: "Backend implementation exercise.",
    candidateId: CANDIDATES[1].id,
    interviewerId: USER.id,
  },
  {
    id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    title: "Alice - Culture Fit",
    type: InterviewType.BEHAVIORAL,
    status: InterviewStatus.SCHEDULED,
    scheduledAtOffset: 14,
    durationMinutes: 30,
    notes: "Team collaboration and communication.",
    candidateId: CANDIDATES[0].id,
    interviewerId: USER.id,
  },
] as const;

export const FEEDBACKS = [
  {
    id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    strengths: "Strong problem-solving skills and clear communication.",
    improvementAreas: "Could develop more system design experience.",
    recommendation: Recommendation.HIRE,
    overallScore: 4,
    technicalScore: 4,
    communicationScore: 4,
    additionalNotes: "Good performance throughout the interview.",
    interviewSessionId: INTERVIEWS[0].id,
    authorId: USER.id,
  },
  {
    id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
    strengths: "Excellent architecture and database design knowledge.",
    improvementAreas: "Hands-on coding speed could improve.",
    recommendation: Recommendation.STRONG_HIRE,
    overallScore: 5,
    technicalScore: 5,
    communicationScore: 4,
    additionalNotes: "Strong candidate for the backend position.",
    interviewSessionId: INTERVIEWS[1].id,
    authorId: USER.id,
  },
  {
    id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
    strengths: "Good coding fundamentals and readable solutions.",
    improvementAreas: "Should add more automated test coverage.",
    recommendation: Recommendation.CONTINUE_PRACTICE,
    overallScore: 3,
    technicalScore: 3,
    communicationScore: 3,
    additionalNotes: "Demonstrated progress during the follow-up.",
    interviewSessionId: INTERVIEWS[4].id,
    authorId: USER.id,
  },
] as const;

export const AUDIT_LOGS = [
  {
    id: "ffffffff-ffff-4fff-8fff-ffffffffffff",
    level: AuditLevel.INFO,
    action: "INTERVIEW_CREATED",
    entityType: "InterviewSession",
    entityId: INTERVIEWS[0].id,
    message: "Demo interview session created.",
    userId: USER.id,
  },
  {
    id: "11111111-aaaa-4aaa-8aaa-11111111aaaa",
    level: AuditLevel.INFO,
    action: "CANDIDATE_CREATED",
    entityType: "Candidate",
    entityId: CANDIDATES[1].id,
    message: "Demo candidate profile created.",
    userId: USER.id,
  },
  {
    id: "22222222-bbbb-4bbb-8bbb-22222222bbbb",
    level: AuditLevel.INFO,
    action: "FEEDBACK_SUBMITTED",
    entityType: "Feedback",
    entityId: FEEDBACKS[0].id,
    message: "Interview feedback submitted.",
    userId: USER.id,
  },
  {
    id: "33333333-cccc-4ccc-8ccc-33333333cccc",
    level: AuditLevel.WARNING,
    action: "INTERVIEW_CANCELLED",
    entityType: "InterviewSession",
    entityId: INTERVIEWS[3].id,
    message: "Demo interview session cancelled.",
    userId: null,
  },
  {
    id: "44444444-dddd-4ddd-8ddd-44444444dddd",
    level: AuditLevel.ERROR,
    action: "NOTIFICATION_FAILED",
    entityType: "InterviewSession",
    entityId: INTERVIEWS[3].id,
    message: "Demo interview reminder delivery failed.",
    userId: null,
  },
] as const;